#!/bin/sh
export FLASK_DEBUG=1
export FLASK_APP=server/slave.py
export PYTHONIOENCODING=utf-8
export PYTHONPATH=$(pwd)
export PID_FILE=slave-1.pid
if [ -f $PID_FILE ]; then
	echo "First slave already running"
	exit 1
fi
echo "[ Perfang Started (First Slave Server) ]"
(
echo Python Path: $PYTHONPATH
# python3 -m flask run --host=0.0.0.0 --port=5001
# python3 server/slave.py & echo $! > $PID_FILE
python3 server/slave.py &
exit
) >> _slave-server.log 2>&1
